# Input the text to decode, generated by Enryption.py
text_coded = input("Enter the code to decipher: ")

dictionary = {"a": 1, "b": 2, "c": 3, "d": 4,"e": 5,"f": 6,"g": 7,"h": 8,"i": 9,"j": 10,"k": 11,
              "l": 12,"m": 13,"n": 14,"o": 15,"p": 16,"q": 17,"r": 18,"s": 19,"t": 20,
              "u": 21,"v": 22,"w": 23,"x": 24,"y": 25,"z": 26, " ": 27, ",": 28, "!": 29, "?": 30,".": 31
             }

inv_dictinary = {v: k for k, v in dictionary.items()}

# Creating an RSA key pair
p = 13 
q = 17 

# Public key n and e
n =p*q 
phi_n = (p-1)*(q-1)
e = 5

#Private key d
i = 2 
d = int((i*phi_n+1)/e) 

# De-Code of numbers
text_coded_number_list_input = text_coded.split(",")[:-1]

text_decoded_number_list = []
for number in text_coded_number_list_input:
    decoded = (int(number)**d)%n 
    text_decoded_number_list.append(decoded)

# Number to letters
text_decoded_list = []
for number in text_decoded_number_list:
    text_decoded_list.append(inv_dictinary[number])

# letters to text
text_decoded = ""
for letter in text_decoded_list:
    text_decoded = text_decoded + letter

# Decoded text
print(text_decoded)